[[plugins]]
repo = "Shougo/dein.vim"

[[plugins]]
repo = "airblade/vim-gitgutter"
hook_add = """
  set updatetime=200
"""

[[plugins]]
repo = "buoto/gotests-vim"

[[plugins]]
repo = "cespare/vim-toml"

[[plugins]]
repo = "cohama/lexima.vim"

[[plugins]]
repo = "easymotion/vim-easymotion"
hook_add = """
  " <Leader>f{char} to move to {char}
  map <Leader>f <Plug>(easymotion-bd-f)
  nmap <Leader>f <Plug>(easymotion-overwin-f)

  " s{char}{char} to move to {char}{char}
  nmap s <Plug>(easymotion-overwin-f2)

  " Move to line
  map<Leader>L <Plug>(easymotion-bd-jk)
  nmap <Leader>L <Plug>(easymotion-overwin-line)

  " Move to word
  map <Leader>W <Plug>(easymotion-bd-w)
  nmap <Leader>W <Plug>(easymotion-overwin-w)
  """

[[plugins]]
repo = "editorconfig/editorconfig-vim"

[[plugins]]
repo = "hrsh7th/vim-vsnip"

[[plugins]]
repo = "hrsh7th/vim-vsnip-integ"

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = """
  let g:lightline = {
  \   "colorscheme": "wombat",
  \ }
"""

[[plugins]]
repo = "junegunn/fzf.vim"

[[plugins]]
repo = "kristijanhusak/defx-git"

[[plugins]]
repo = "kristijanhusak/defx-icons"

[[plugins]]
repo = "mattn/vim-goimports"

[[plugins]]
repo = "mattn/vim-lsp-icons"

[[plugins]]
repo = "mattn/vim-lsp-settings"

[[plugins]]
repo = "prabirshrestha/async.vim"

[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"
hook_add = """
  let g:asyncomplete_auto_completeopt = 0
  let g:asyncomplete_auto_popup = 1
  let g:asyncomplete_popup_delay = 200
"""

[[plugins]]
repo = "prabirshrestha/asyncomplete-lsp.vim"

[[plugins]]
repo = "prabirshrestha/vim-lsp"
hook_add = """
  let lsp_signature_help_enabled = 1
  nnoremap <silent> <f2> :LspRename<CR>
  nnoremap <silent> gd :LspDefinition<CR>
"""

[[plugins]]
repo = "prettier/vim-prettier"
rev = "release/2.x"
build = "yarn install"

[[plugins]]
repo = "psf/black"
hook_add = """
  autocmd BufWritePre *.py execute ":Black"
  let g:black_virtualenv = "~/.local/share/nvim/black"
"""

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo = "Shougo/defx.nvim"
hook_add = """
  nnoremap <C-e> :Defx<CR>
"""

[[plugins]]
repo = "Shougo/deoplete.nvim"
hook_add = """
  let g:deoplete#enable_at_startup = 1
"""

[[plugins]]
repo = "Shougo/vimproc.vim"
build = "make"

[[plugins]]
repo = "terryma/vim-multiple-cursors"

[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = """
  let g:quickrun_config = {
  \   "_": {
  \     "outputter/buffer/split": ":botright 8",
  \   }
  \ }

  nnoremap <Leader>e :QuickRun<CR>
  nnoremap <Leader>E :QuickRun -input =@+<CR>
"""

[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = """
  nnoremap <leader>ga :Git add %:p<CR><CR>
  nnoremap <leader>gb :Gblame<CR>
  nnoremap <leader>gc :Gcommit<CR><CR>
  nnoremap <leader>gd :Gdiff<CR>
  nnoremap <leader>gl :Glog<CR>
  nnoremap <leader>gp :Gpush<CR>
  nnoremap <leader>gs :Gstatus<CR>
"""

[[plugins]]
repo = "tyru/open-browser.vim"

[[plugins]]
repo = "wakatime/vim-wakatime"
